import {
  Profile,
  School,
  SubscriptionPlan,
  ClassRoom,
  Section,
  Subject,
  Teacher,
  Student,
  AttendanceRecord,
  FeeStructure,
  FeePayment,
  Exam,
  ExamSubject,
  MarkRecord,
  ExamResult,
  DocumentTemplate,
  GeneratedDocument,
  Notice,
  Homework,
  TimetableEntry,
  AuditLog,
  AdmissionApplication,
  SchoolSettings,
  SchoolTemplate,
} from '../types/database';

import { MASTER_TEMPLATES } from './template-registry';

export const INITIAL_PLANS: SubscriptionPlan[] = [
  {
    id: '11111111-1111-1111-1111-111111111101',
    name: 'Don Bosco Academy Enterprise',
    slug: 'don-bosco-enterprise',
    price_monthly: 0,
    price_yearly: 0,
    max_students: 5000,
    max_teachers: 250,
    max_storage_mb: 50000,
    features: {
      qr_verification: true,
      custom_templates: true,
      bulk_documents: true,
      sms_alerts: true,
      white_label: true,
      custom_domain: true,
    },
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_TEMPLATES: DocumentTemplate[] = MASTER_TEMPLATES;

export const DON_BOSCO_SCHOOL_ID = 'sch-don-bosco';

export const INITIAL_SCHOOLS: School[] = [
  {
    id: DON_BOSCO_SCHOOL_ID,
    name: 'DON BOSCO ACADEMY',
    slug: 'don-bosco-academy',
    email: 'donboscoacademy002@gmail.com',
    phone: '+91 91024 35126',
    address: 'Raipur Bazar, Nanpur, Sitamarhi',
    city: 'Sitamarhi',
    state: 'Bihar',
    country: 'India',
    postal_code: '843326',
    principal_name: 'Md. Shami Ahmad',
    logo_url: '/assets/branding/don-bosco-logo.png',
    banner_url: '/assets/branding/main-banner.svg',
    admission_banner_url: '/assets/branding/admission-banner.svg',
    announcement_banner_url: '/assets/branding/main-banner.svg',
    header_banner_url: '/assets/branding/main-banner.svg',
    certificate_bg_url: '/official-certificate-border.jpg',
    marksheet_bg_url: '/official-certificate-border.jpg',
    principal_photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300',
    principal_signature_url: '/assets/branding/principal-signature.svg',
    stamp_url: '/assets/branding/don-bosco-stamp.svg',
    tagline: 'KNOWLEDGE IS POWER',
    established_year: '1997',
    school_type: 'Residential Cum Day School',
    academic_pattern: 'CBSE Pattern',
    classes_offered: 'Play to Class 10th',
    facebook_url: 'https://www.facebook.com/donboscoacademy002',
    about: 'Established in 1997, DON BOSCO ACADEMY is a premier Residential Cum Day School in Raipur Bazar, Nanpur, Sitamarhi (Bihar). Operating on the CBSE pattern from Play Group to Class 10th, we are committed to holistic academic excellence, character building, modern technology-enabled learning, and disciplinary strength.',
    website: 'https://donboscoacademy.edu.in',
    status: 'active',
    subscription_plan_id: '11111111-1111-1111-1111-111111111101',
    created_at: '1997-04-01T00:00:00.000Z',
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_SCHOOL_SETTINGS: Record<string, SchoolSettings> = {
  [DON_BOSCO_SCHOOL_ID]: {
    school_id: DON_BOSCO_SCHOOL_ID,
    grading_system: [
      { grade: 'A1', min_percentage: 91, max_percentage: 100, gpa: 10.0, description: 'Outstanding Top Distinction' },
      { grade: 'A2', min_percentage: 81, max_percentage: 90, gpa: 9.0, description: 'Excellent Performance' },
      { grade: 'B1', min_percentage: 71, max_percentage: 80, gpa: 8.0, description: 'Very Good' },
      { grade: 'B2', min_percentage: 61, max_percentage: 70, gpa: 7.0, description: 'Good' },
      { grade: 'C1', min_percentage: 51, max_percentage: 60, gpa: 6.0, description: 'Satisfactory / Above Average' },
      { grade: 'C2', min_percentage: 41, max_percentage: 50, gpa: 5.0, description: 'Average' },
      { grade: 'D', min_percentage: 33, max_percentage: 40, gpa: 4.0, description: 'Marginal / Pass' },
      { grade: 'E', min_percentage: 0, max_percentage: 32, gpa: 0.0, description: 'Essential Repeat / Fail' },
    ],
    attendance_type: 'daily',
    currency_symbol: '₹',
    timezone: 'Asia/Kolkata',
    date_format: 'DD/MM/YYYY',
    theme_color: '#1e3a8a',
    numbering_patterns: {
      marksheet_pattern: 'DBA/{CLASS}/{YEAR}/MS-{SEQ}',
      certificate_pattern: 'DBA/{CLASS}/{YEAR}/{SEQ}',
      admit_card_pattern: 'DBA/AC/{CLASS}/{YEAR}/{SEQ}',
      id_card_pattern: 'DBA/ID/{YEAR}/{ROLL}',
      current_sequence: 101,
    },
    default_certificate_body: 'In recognition of outstanding scholastic achievement, ranking 1st in Class 10 with distinguished merit in the Academic Year 2025-2026.',
    default_marksheet_remarks: 'Outstanding performance. Promoted to next higher class with distinction.',
    updated_at: new Date().toISOString(),
  },
};

export const INITIAL_ACADEMIC_SESSIONS = [
  {
    id: 'sess-2026',
    school_id: DON_BOSCO_SCHOOL_ID,
    name: '2026-2027',
    start_date: '2026-04-01',
    end_date: '2027-03-31',
    is_current: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'sess-2025',
    school_id: DON_BOSCO_SCHOOL_ID,
    name: '2025-2026',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
    is_current: false,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_CLASSES: ClassRoom[] = [
  { id: 'class-play', school_id: DON_BOSCO_SCHOOL_ID, name: 'Play Group', numeric_grade: 0, class_teacher_name: 'Mrs. Shabana Khatoon', created_at: new Date().toISOString() },
  { id: 'class-nursery', school_id: DON_BOSCO_SCHOOL_ID, name: 'Nursery', numeric_grade: 0, class_teacher_name: 'Mrs. Anjali Kumari', created_at: new Date().toISOString() },
  { id: 'class-lkg', school_id: DON_BOSCO_SCHOOL_ID, name: 'LKG', numeric_grade: 0, class_teacher_name: 'Ms. Pooja Sharma', created_at: new Date().toISOString() },
  { id: 'class-ukg', school_id: DON_BOSCO_SCHOOL_ID, name: 'UKG', numeric_grade: 0, class_teacher_name: 'Mrs. Farhana Begum', created_at: new Date().toISOString() },
  { id: 'class-1', school_id: DON_BOSCO_SCHOOL_ID, name: 'Class 1', numeric_grade: 1, class_teacher_name: 'Mr. Rajesh Kumar', created_at: new Date().toISOString() },
  { id: 'class-2', school_id: DON_BOSCO_SCHOOL_ID, name: 'Class 2', numeric_grade: 2, class_teacher_name: 'Mrs. Suman Lata', created_at: new Date().toISOString() },
  { id: 'class-3', school_id: DON_BOSCO_SCHOOL_ID, name: 'Class 3', numeric_grade: 3, class_teacher_name: 'Mr. Arvind Singh', created_at: new Date().toISOString() },
  { id: 'class-4', school_id: DON_BOSCO_SCHOOL_ID, name: 'Class 4', numeric_grade: 4, class_teacher_name: 'Mrs. Nazia Parveen', created_at: new Date().toISOString() },
  { id: 'class-5', school_id: DON_BOSCO_SCHOOL_ID, name: 'Class 5', numeric_grade: 5, class_teacher_name: 'Mr. Santosh Kumar', created_at: new Date().toISOString() },
  { id: 'class-6', school_id: DON_BOSCO_SCHOOL_ID, name: 'Class 6', numeric_grade: 6, class_teacher_name: 'Mr. Tariq Anwar', created_at: new Date().toISOString() },
  { id: 'class-7', school_id: DON_BOSCO_SCHOOL_ID, name: 'Class 7', numeric_grade: 7, class_teacher_name: 'Mr. Deepak Mishra', created_at: new Date().toISOString() },
  { id: 'class-8', school_id: DON_BOSCO_SCHOOL_ID, name: 'Class 8', numeric_grade: 8, class_teacher_name: 'Mr. Manoj Thakur', created_at: new Date().toISOString() },
  { id: 'class-9', school_id: DON_BOSCO_SCHOOL_ID, name: 'Class 9', numeric_grade: 9, class_teacher_name: 'Mr. Afroz Alam', created_at: new Date().toISOString() },
  { id: 'class-10', school_id: DON_BOSCO_SCHOOL_ID, name: 'Class 10', numeric_grade: 10, class_teacher_name: 'Md. Shami Ahmad', created_at: new Date().toISOString() },
];

export const INITIAL_SECTIONS: Section[] = [
  { id: 'sec-10-a', school_id: DON_BOSCO_SCHOOL_ID, class_id: 'class-10', name: 'A', room_no: 'Room 101', capacity: 45, created_at: new Date().toISOString() },
  { id: 'sec-10-b', school_id: DON_BOSCO_SCHOOL_ID, class_id: 'class-10', name: 'B', room_no: 'Room 102', capacity: 45, created_at: new Date().toISOString() },
  { id: 'sec-9-a', school_id: DON_BOSCO_SCHOOL_ID, class_id: 'class-9', name: 'A', room_no: 'Room 201', capacity: 45, created_at: new Date().toISOString() },
  { id: 'sec-9-b', school_id: DON_BOSCO_SCHOOL_ID, class_id: 'class-9', name: 'B', room_no: 'Room 202', capacity: 45, created_at: new Date().toISOString() },
  { id: 'sec-8-a', school_id: DON_BOSCO_SCHOOL_ID, class_id: 'class-8', name: 'A', room_no: 'Room 203', capacity: 40, created_at: new Date().toISOString() },
  { id: 'sec-1-a', school_id: DON_BOSCO_SCHOOL_ID, class_id: 'class-1', name: 'A', room_no: 'Primary Block 1', capacity: 35, created_at: new Date().toISOString() },
  { id: 'sec-play-a', school_id: DON_BOSCO_SCHOOL_ID, class_id: 'class-play', name: 'A', room_no: 'Activity Room', capacity: 30, created_at: new Date().toISOString() },
];

export const INITIAL_SUBJECTS: Subject[] = [
  { id: 'sub-math', school_id: DON_BOSCO_SCHOOL_ID, name: 'Mathematics', code: 'MATH-101', type: 'both', created_at: new Date().toISOString() },
  { id: 'sub-sci', school_id: DON_BOSCO_SCHOOL_ID, name: 'Science & Practical Lab', code: 'SCI-102', type: 'both', created_at: new Date().toISOString() },
  { id: 'sub-eng', school_id: DON_BOSCO_SCHOOL_ID, name: 'English Language & Literature', code: 'ENG-103', type: 'theory', created_at: new Date().toISOString() },
  { id: 'sub-hin', school_id: DON_BOSCO_SCHOOL_ID, name: 'Hindi Course A', code: 'HIN-104', type: 'theory', created_at: new Date().toISOString() },
  { id: 'sub-sst', school_id: DON_BOSCO_SCHOOL_ID, name: 'Social Science (History/Geo/Pol.Sci/Eco)', code: 'SST-105', type: 'both', created_at: new Date().toISOString() },
  { id: 'sub-cs', school_id: DON_BOSCO_SCHOOL_ID, name: 'Information Technology & AI', code: 'IT-106', type: 'both', created_at: new Date().toISOString() },
  { id: 'sub-san', school_id: DON_BOSCO_SCHOOL_ID, name: 'Sanskrit / Urdu', code: 'SKT-107', type: 'theory', created_at: new Date().toISOString() },
];

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 'tch-1',
    school_id: DON_BOSCO_SCHOOL_ID,
    employee_id: 'DBA-T001',
    first_name: 'Md. Shami',
    last_name: 'Ahmad',
    designation: 'Senior Faculty & Mathematics Head',
    qualification: 'M.Sc. Mathematics, B.Ed.',
    phone: '+91 91024 35126',
    email: 'donboscoacademy002@gmail.com',
    joining_date: '2010-06-15',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 'tch-2',
    school_id: DON_BOSCO_SCHOOL_ID,
    employee_id: 'DBA-T002',
    first_name: 'Afroz',
    last_name: 'Alam',
    designation: 'Science Faculty & Lab Coordinator',
    qualification: 'M.Sc. Chemistry, B.Ed.',
    phone: '+91 98350 12345',
    email: 'afroz@donboscoacademy.edu.in',
    joining_date: '2015-07-01',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    status: 'active',
    created_at: new Date().toISOString(),
  },
  {
    id: 'tch-3',
    school_id: DON_BOSCO_SCHOOL_ID,
    employee_id: 'DBA-T003',
    first_name: 'Deepak',
    last_name: 'Mishra',
    designation: 'English Literature Faculty',
    qualification: 'M.A. English, B.Ed.',
    phone: '+91 94312 67890',
    email: 'deepak@donboscoacademy.edu.in',
    joining_date: '2018-04-10',
    photo_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    status: 'active',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'stu-1',
    school_id: DON_BOSCO_SCHOOL_ID,
    admission_number: 'DBA-2026-001',
    roll_number: '1001',
    first_name: 'Aman',
    middle_name: 'Kumar',
    last_name: 'Singh',
    gender: 'Male',
    date_of_birth: '2011-05-14',
    blood_group: 'B+',
    photo_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    father_name: 'Ramesh Singh',
    mother_name: 'Sunita Devi',
    parent_phone: '+91 98765 43210',
    parent_email: 'ramesh.singh@example.com',
    address: 'Raipur Bazar, Nanpur, Sitamarhi, Bihar',
    city: 'Sitamarhi',
    state: 'Bihar',
    admission_date: '2020-04-15',
    current_class_id: 'class-10',
    current_section_id: 'sec-10-a',
    status: 'active',
    class_name: 'Class 10',
    section_name: 'A',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'stu-2',
    school_id: DON_BOSCO_SCHOOL_ID,
    admission_number: 'DBA-2026-002',
    roll_number: '1002',
    first_name: 'Fatima',
    last_name: 'Zehra',
    gender: 'Female',
    date_of_birth: '2011-09-20',
    blood_group: 'O+',
    photo_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    father_name: 'Md. Tariq',
    mother_name: 'Farzana Begum',
    parent_phone: '+91 91234 56789',
    parent_email: 'tariq.sitamarhi@example.com',
    address: 'Main Road, Nanpur, Sitamarhi, Bihar',
    city: 'Sitamarhi',
    state: 'Bihar',
    admission_date: '2020-04-15',
    current_class_id: 'class-10',
    current_section_id: 'sec-10-a',
    status: 'active',
    class_name: 'Class 10',
    section_name: 'A',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'stu-3',
    school_id: DON_BOSCO_SCHOOL_ID,
    admission_number: 'DBA-2026-003',
    roll_number: '1003',
    first_name: 'Rahul',
    last_name: 'Kumar',
    gender: 'Male',
    date_of_birth: '2012-01-18',
    blood_group: 'AB+',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    father_name: 'Manoj Kumar',
    mother_name: 'Kavita Devi',
    parent_phone: '+91 98350 98765',
    parent_email: 'manoj.k@example.com',
    address: 'Bazar Samiti Road, Raipur, Sitamarhi',
    city: 'Sitamarhi',
    state: 'Bihar',
    admission_date: '2021-04-10',
    current_class_id: 'class-9',
    current_section_id: 'sec-9-a',
    status: 'active',
    class_name: 'Class 9',
    section_name: 'A',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam-annual-2026',
    school_id: DON_BOSCO_SCHOOL_ID,
    session_id: 'sess-2025',
    name: 'Annual Examination 2025-2026',
    exam_type: 'Annual',
    start_date: '2026-03-01',
    end_date: '2026-03-15',
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'exam-midterm-2026',
    school_id: DON_BOSCO_SCHOOL_ID,
    session_id: 'sess-2026',
    name: 'Mid-Term Periodic Assessment 2026',
    exam_type: 'Term',
    start_date: '2026-09-20',
    end_date: '2026-09-30',
    is_published: true,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_EXAM_SUBJECTS: ExamSubject[] = [
  {
    id: 'es-1',
    school_id: DON_BOSCO_SCHOOL_ID,
    exam_id: 'exam-annual-2026',
    class_id: 'class-10',
    subject_id: 'sub-math',
    exam_date: '2026-03-02',
    start_time: '09:00',
    end_time: '12:00',
    max_theory_marks: 80,
    max_practical_marks: 20,
    pass_marks: 33,
    subject_name: 'Mathematics',
    subject_code: 'MATH-101',
    class_name: 'Class 10',
    created_at: new Date().toISOString(),
  },
  {
    id: 'es-2',
    school_id: DON_BOSCO_SCHOOL_ID,
    exam_id: 'exam-annual-2026',
    class_id: 'class-10',
    subject_id: 'sub-sci',
    exam_date: '2026-03-04',
    start_time: '09:00',
    end_time: '12:00',
    max_theory_marks: 70,
    max_practical_marks: 30,
    pass_marks: 33,
    subject_name: 'Science & Practical Lab',
    subject_code: 'SCI-102',
    class_name: 'Class 10',
    created_at: new Date().toISOString(),
  },
  {
    id: 'es-3',
    school_id: DON_BOSCO_SCHOOL_ID,
    exam_id: 'exam-annual-2026',
    class_id: 'class-10',
    subject_id: 'sub-eng',
    exam_date: '2026-03-07',
    start_time: '09:00',
    end_time: '12:00',
    max_theory_marks: 80,
    max_practical_marks: 20,
    pass_marks: 33,
    subject_name: 'English Language & Literature',
    subject_code: 'ENG-103',
    class_name: 'Class 10',
    created_at: new Date().toISOString(),
  },
  {
    id: 'es-4',
    school_id: DON_BOSCO_SCHOOL_ID,
    exam_id: 'exam-annual-2026',
    class_id: 'class-10',
    subject_id: 'sub-hin',
    exam_date: '2026-03-09',
    start_time: '09:00',
    end_time: '12:00',
    max_theory_marks: 80,
    max_practical_marks: 20,
    pass_marks: 33,
    subject_name: 'Hindi Course A',
    subject_code: 'HIN-104',
    class_name: 'Class 10',
    created_at: new Date().toISOString(),
  },
  {
    id: 'es-5',
    school_id: DON_BOSCO_SCHOOL_ID,
    exam_id: 'exam-annual-2026',
    class_id: 'class-10',
    subject_id: 'sub-sst',
    exam_date: '2026-03-12',
    start_time: '09:00',
    end_time: '12:00',
    max_theory_marks: 80,
    max_practical_marks: 20,
    pass_marks: 33,
    subject_name: 'Social Science',
    subject_code: 'SST-105',
    class_name: 'Class 10',
    created_at: new Date().toISOString(),
  },
  {
    id: 'es-6',
    school_id: DON_BOSCO_SCHOOL_ID,
    exam_id: 'exam-annual-2026',
    class_id: 'class-10',
    subject_id: 'sub-cs',
    exam_date: '2026-03-14',
    start_time: '09:00',
    end_time: '12:00',
    max_theory_marks: 50,
    max_practical_marks: 50,
    pass_marks: 33,
    subject_name: 'Information Technology & AI',
    subject_code: 'IT-106',
    class_name: 'Class 10',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_MARKS: MarkRecord[] = [
  { id: 'mk-1', school_id: DON_BOSCO_SCHOOL_ID, exam_subject_id: 'es-1', student_id: 'stu-1', theory_marks: 75, practical_marks: 19, total_marks: 94, grade: 'A1', is_absent: false, created_at: new Date().toISOString() },
  { id: 'mk-2', school_id: DON_BOSCO_SCHOOL_ID, exam_subject_id: 'es-2', student_id: 'stu-1', theory_marks: 65, practical_marks: 29, total_marks: 94, grade: 'A1', is_absent: false, created_at: new Date().toISOString() },
  { id: 'mk-3', school_id: DON_BOSCO_SCHOOL_ID, exam_subject_id: 'es-3', student_id: 'stu-1', theory_marks: 74, practical_marks: 18, total_marks: 92, grade: 'A1', is_absent: false, created_at: new Date().toISOString() },
  { id: 'mk-4', school_id: DON_BOSCO_SCHOOL_ID, exam_subject_id: 'es-4', student_id: 'stu-1', theory_marks: 76, practical_marks: 19, total_marks: 95, grade: 'A1', is_absent: false, created_at: new Date().toISOString() },
  { id: 'mk-5', school_id: DON_BOSCO_SCHOOL_ID, exam_subject_id: 'es-5', student_id: 'stu-1', theory_marks: 72, practical_marks: 18, total_marks: 90, grade: 'A2', is_absent: false, created_at: new Date().toISOString() },
  { id: 'mk-6', school_id: DON_BOSCO_SCHOOL_ID, exam_subject_id: 'es-6', student_id: 'stu-1', theory_marks: 48, practical_marks: 49, total_marks: 97, grade: 'A1', is_absent: false, created_at: new Date().toISOString() },
];

export const INITIAL_RESULTS: ExamResult[] = [
  {
    id: 'res-1',
    school_id: DON_BOSCO_SCHOOL_ID,
    exam_id: 'exam-annual-2026',
    student_id: 'stu-1',
    class_id: 'class-10',
    total_max_marks: 600,
    total_obtained_marks: 562,
    percentage: 93.67,
    gpa: 9.8,
    grade: 'A1',
    result_status: 'PASS',
    rank_in_class: 1,
    remarks: 'Outstanding scholastic excellence and exemplary leadership in Don Bosco Academy.',
    created_at: new Date().toISOString(),
    student: INITIAL_STUDENTS[0],
  },
  {
    id: 'res-2',
    school_id: DON_BOSCO_SCHOOL_ID,
    exam_id: 'exam-annual-2026',
    student_id: 'stu-2',
    class_id: 'class-10',
    total_max_marks: 600,
    total_obtained_marks: 538,
    percentage: 89.67,
    gpa: 9.0,
    grade: 'A2',
    result_status: 'PASS',
    rank_in_class: 2,
    remarks: 'Brilliant conceptual clarity and disciplined academic participation.',
    created_at: new Date().toISOString(),
    student: INITIAL_STUDENTS[1],
  },
];

export const INITIAL_SCHOOL_TEMPLATES: SchoolTemplate[] = [
  {
    id: 'dba-ms',
    school_id: DON_BOSCO_SCHOOL_ID,
    category: 'MARKSHEET',
    template_id: 'tmpl-marksheet-01',
    custom_config: {},
    is_active: true,
    updated_at: new Date().toISOString(),
    template: INITIAL_TEMPLATES.find((t) => t.id === 'tmpl-marksheet-01') || INITIAL_TEMPLATES[0],
  },
  {
    id: 'dba-cert',
    school_id: DON_BOSCO_SCHOOL_ID,
    category: 'CERTIFICATE',
    template_id: 'tmpl-cert-01',
    custom_config: {},
    is_active: true,
    updated_at: new Date().toISOString(),
    template: INITIAL_TEMPLATES.find((t) => t.id === 'tmpl-cert-01') || INITIAL_TEMPLATES[5],
  },
  {
    id: 'dba-admit',
    school_id: DON_BOSCO_SCHOOL_ID,
    category: 'ADMIT_CARD',
    template_id: 'tmpl-admit-01',
    custom_config: {},
    is_active: true,
    updated_at: new Date().toISOString(),
    template: INITIAL_TEMPLATES.find((t) => t.id === 'tmpl-admit-01') || INITIAL_TEMPLATES[10],
  },
  {
    id: 'dba-id',
    school_id: DON_BOSCO_SCHOOL_ID,
    category: 'ID_CARD',
    template_id: 'tmpl-id-01',
    custom_config: {},
    is_active: true,
    updated_at: new Date().toISOString(),
    template: INITIAL_TEMPLATES.find((t) => t.id === 'tmpl-id-01') || INITIAL_TEMPLATES[15],
  },
];

export const INITIAL_GENERATED_DOCUMENTS: GeneratedDocument[] = [
  {
    id: 'doc-cert-0103',
    school_id: DON_BOSCO_SCHOOL_ID,
    student_id: 'stu-1',
    template_id: 'tmpl-cert-01',
    doc_type: 'CERTIFICATE',
    certificate_no: 'DBA-CERT-2026-0103',
    verification_code: 'DBA-CERT-2026-0103',
    title: 'Certificate of Academic Merit & Distinction',
    metadata: {
      student_name: 'MD Shami Ahmad',
      father_name: 'Shabbir Ahmad',
      mother_name: 'Fatima Begum',
      class_name: 'Class 10',
      section_name: 'A',
      roll_number: '1001',
      admission_number: 'DBA-2026-001',
      course_type: 'CBSE Secondary School Examination (Class X)',
      academic_session: '2025-2026',
      issued_date: '15/03/2026',
      certificate_body: 'In recognition of outstanding scholastic achievement, distinguished merit and exemplary discipline at Don Bosco Academy in the Academic Session 2025-2026.',
    },
    status: 'VALID',
    issued_at: new Date().toISOString(),
    student: INITIAL_STUDENTS[0],
    school: INITIAL_SCHOOLS[0],
  },
  {
    id: 'doc-mark-0103',
    school_id: DON_BOSCO_SCHOOL_ID,
    student_id: 'stu-1',
    template_id: 'tmpl-marksheet-01',
    doc_type: 'MARKSHEET',
    certificate_no: 'DBA-MARK-2026-0103',
    verification_code: 'DBA-MARK-2026-0103',
    title: 'Official CBSE Class X Marksheet 2026',
    metadata: {
      student_name: 'MD Shami Ahmad',
      father_name: 'Shabbir Ahmad',
      mother_name: 'Fatima Begum',
      class_name: 'Class 10',
      section_name: 'A',
      roll_number: '1001',
      admission_number: 'DBA-2026-001',
      academic_session: '2025-2026',
      exam_name: 'CBSE Class X Annual Examination 2026',
      total_marks: 566,
      max_marks: 600,
      percentage: 94.33,
      grade: 'A1',
      division: '1st Division with Distinction',
      result: 'PASSED WITH DISTINCTION (RANK #1)',
      marks: [
        { subject: 'English Language & Literature', max: 100, pass_marks: 33, theory: 74, practical: 20, total: 94, grade: 'A1' },
        { subject: 'Mathematics (Standard)', max: 100, pass_marks: 33, theory: 78, practical: 20, total: 98, grade: 'A1' },
        { subject: 'Science (Physics, Chem, Bio)', max: 100, pass_marks: 33, theory: 72, practical: 20, total: 92, grade: 'A1' },
        { subject: 'Social Science', max: 100, pass_marks: 33, theory: 71, practical: 19, total: 90, grade: 'A1' },
        { subject: 'Hindi Course-A', max: 100, pass_marks: 33, theory: 76, practical: 19, total: 95, grade: 'A1' },
        { subject: 'Computer Applications & AI', max: 100, pass_marks: 33, theory: 48, practical: 49, total: 97, grade: 'A1' },
      ],
    },
    status: 'VALID',
    issued_at: new Date().toISOString(),
    student: INITIAL_STUDENTS[0],
    school: INITIAL_SCHOOLS[0],
  },
  {
    id: 'doc-cert-revoked-01',
    school_id: DON_BOSCO_SCHOOL_ID,
    student_id: 'stu-1',
    template_id: 'tmpl-cert-01',
    doc_type: 'CERTIFICATE',
    certificate_no: 'DBA-CERT-2026-REVOKED',
    verification_code: 'DBA-CERT-2026-REVOKED',
    title: 'Revoked Certificate Record',
    metadata: {
      student_name: 'MD Shami Ahmad',
      father_name: 'Shabbir Ahmad',
      class_name: 'Class 10',
      academic_session: '2025-2026',
    },
    status: 'REVOKED',
    revoked_at: new Date().toISOString(),
    revocation_reason: 'Revoked by school administration due to issuance of updated credentials.',
    issued_at: new Date().toISOString(),
    student: INITIAL_STUDENTS[0],
    school: INITIAL_SCHOOLS[0],
  },
  {
    id: 'doc-mark-revoked-01',
    school_id: DON_BOSCO_SCHOOL_ID,
    student_id: 'stu-1',
    template_id: 'tmpl-marksheet-01',
    doc_type: 'MARKSHEET',
    certificate_no: 'DBA-MARK-2026-REVOKED',
    verification_code: 'DBA-MARK-2026-REVOKED',
    title: 'Revoked Marksheet Record',
    metadata: {
      student_name: 'MD Shami Ahmad',
      father_name: 'Shabbir Ahmad',
      class_name: 'Class 10',
      academic_session: '2025-2026',
    },
    status: 'REVOKED',
    revoked_at: new Date().toISOString(),
    revocation_reason: 'Revoked by examination board pending marks re-evaluation.',
    issued_at: new Date().toISOString(),
    student: INITIAL_STUDENTS[0],
    school: INITIAL_SCHOOLS[0],
  },
];

export const INITIAL_FEE_STRUCTURES: FeeStructure[] = [
  {
    id: 'fee-quarterly-1',
    school_id: DON_BOSCO_SCHOOL_ID,
    session_id: 'sess-2026',
    title: 'Quarter 1 Tuition & Lab Maintenance Fee',
    amount: 3200,
    due_date: '2026-05-15',
    frequency: 'quarterly',
    class_name: 'Class 10',
    created_at: new Date().toISOString(),
  },
  {
    id: 'fee-hostel-1',
    school_id: DON_BOSCO_SCHOOL_ID,
    session_id: 'sess-2026',
    title: 'Residential Hostel & Boarding Fee (Monthly)',
    amount: 4500,
    due_date: '2026-04-10',
    frequency: 'monthly',
    class_name: 'Class 10',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_FEE_PAYMENTS: FeePayment[] = [
  {
    id: 'pay-1',
    school_id: DON_BOSCO_SCHOOL_ID,
    student_id: 'stu-1',
    fee_structure_id: 'fee-quarterly-1',
    receipt_no: 'DBA-REC-2026-001',
    amount_paid: 3200,
    discount: 0,
    fine: 0,
    payment_method: 'UPI',
    transaction_ref: 'UPI-DBA-910243',
    payment_date: '2026-04-12',
    status: 'paid',
    fee_title: 'Quarter 1 Tuition & Lab Maintenance Fee',
    student: INITIAL_STUDENTS[0],
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'not-1',
    school_id: DON_BOSCO_SCHOOL_ID,
    title: 'Admissions Open for Academic Session 2026-2027 (Play to Class 10th)',
    content: 'Registration and admission forms for the 2026-2027 session are now available online and at the school administrative counter in Raipur Bazar, Nanpur, Sitamarhi. Limited residential hostel seats available.',
    target_role: 'ALL',
    is_pinned: true,
    publish_date: '2026-04-01',
    created_at: new Date().toISOString(),
  },
  {
    id: 'not-2',
    school_id: DON_BOSCO_SCHOOL_ID,
    title: 'CBSE Pattern Annual Board Preparation Workshop',
    content: 'Special evening doubt-clearing and board test sessions for Class 9th and 10th commence this Monday in the Science Wing.',
    target_role: 'STUDENT',
    is_pinned: true,
    publish_date: '2026-04-05',
    created_at: new Date().toISOString(),
  },
  {
    id: 'not-3',
    school_id: DON_BOSCO_SCHOOL_ID,
    title: 'Don Bosco Academy Annual Sports & Cultural Meet',
    content: 'Inter-house football, cricket, athletics, and cultural drama competitions will be held at the main campus ground.',
    target_role: 'ALL',
    is_pinned: false,
    publish_date: '2026-04-10',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_HOMEWORK: Homework[] = [
  {
    id: 'hw-1',
    school_id: DON_BOSCO_SCHOOL_ID,
    class_id: 'class-10',
    subject_id: 'sub-math',
    title: 'CBSE Mathematics: Real Numbers & Polynomials',
    description: 'Solve NCERT Exercise 1.2 and 2.1 in class notebook. Submit the solved step-by-step proofs for verification.',
    assigned_date: '2026-04-15',
    due_date: '2026-04-20',
    class_name: 'Class 10',
    subject_name: 'Mathematics',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_TIMETABLES: TimetableEntry[] = [
  { id: 'tt-1', school_id: DON_BOSCO_SCHOOL_ID, class_id: 'class-10', subject_id: 'sub-math', day_of_week: 'Monday', period_number: 1, start_time: '08:00', end_time: '08:45', room_no: 'Room 101', subject_name: 'Mathematics', teacher_name: 'Md. Shami Ahmad' },
  { id: 'tt-2', school_id: DON_BOSCO_SCHOOL_ID, class_id: 'class-10', subject_id: 'sub-sci', day_of_week: 'Monday', period_number: 2, start_time: '08:50', end_time: '09:35', room_no: 'Science Lab', subject_name: 'Science & Practical Lab', teacher_name: 'Mr. Afroz Alam' },
  { id: 'tt-3', school_id: DON_BOSCO_SCHOOL_ID, class_id: 'class-10', subject_id: 'sub-eng', day_of_week: 'Monday', period_number: 3, start_time: '09:40', end_time: '10:25', room_no: 'Room 101', subject_name: 'English Language & Literature', teacher_name: 'Mr. Deepak Mishra' },
  { id: 'tt-4', school_id: DON_BOSCO_SCHOOL_ID, class_id: 'class-10', subject_id: 'sub-cs', day_of_week: 'Monday', period_number: 4, start_time: '10:45', end_time: '11:30', room_no: 'Computer Lab', subject_name: 'Information Technology & AI', teacher_name: 'Md. Shami Ahmad' },
];

export const INITIAL_ADMISSIONS: AdmissionApplication[] = [
  {
    id: 'adm-1',
    school_id: DON_BOSCO_SCHOOL_ID,
    application_no: 'DBA-APP-2026-101',
    student_name: 'Zaid Akhtar',
    dob: '2015-06-12',
    gender: 'Male',
    applying_class_id: 'class-6',
    previous_school: 'St. Joseph Academy, Sitamarhi',
    parent_name: 'Akhtar Hussain',
    parent_phone: '+91 98350 44556',
    parent_email: 'akhtar.h@example.com',
    status: 'pending',
    class_name: 'Class 6',
    created_at: new Date().toISOString(),
  },
  {
    id: 'adm-2',
    school_id: DON_BOSCO_SCHOOL_ID,
    application_no: 'DBA-APP-2026-102',
    student_name: 'Priya Sharma',
    dob: '2020-08-10',
    gender: 'Female',
    applying_class_id: 'class-play',
    previous_school: 'Home / Playschool',
    parent_name: 'Ravi Sharma',
    parent_phone: '+91 94312 88990',
    parent_email: 'ravi.sharma@example.com',
    status: 'approved',
    class_name: 'Play Group',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    school_id: DON_BOSCO_SCHOOL_ID,
    user_email: 'donboscoacademy002@gmail.com',
    action: 'INIT_SYSTEM',
    resource_type: 'SYSTEM',
    resource_id: DON_BOSCO_SCHOOL_ID,
    details: { school_name: 'DON BOSCO ACADEMY', established: 1997, location: 'Raipur Bazar, Nanpur, Sitamarhi' },
    created_at: new Date().toISOString(),
  },
];
